### ISSUE TITLE
Dual Boot: Boot from disk image only working when USB attached - from HD/SSD only = reboot

### ISSUE THREAD

**Issue by ericksontx** [sebanc/crunch#2]
Hi, installed Crunch successfully to USB and booting from USB is working fine, and also installed to internal SSD and under the Dual Boot instructions (attempting to do a dual boot Windows/Chrome machine) added the boot from disk image option to my grub menu.

Boot from disk image, when booting from USB, works fine. Using Eve/Pixelbook with MrChromebox BIOS.

However when I attempt to boot from JUST disk (USB removed), like when I add that same "boot from disk image" grub entry information from the crunch script output to a new EFI entry, or boot from an EFI bootmanager like Grub2Win with that new EFI boot entry, it results in a black screen for a few seconds, then a reboot.

Any ideas? Thanks.

menuentry "ChromeOS (boot from disk image)" {
        img_part=/dev/nvme0n1p5
        img_path=/chromeos.img
        search --no-floppy --set=root --file $img_path
        loopback loop $img_path
        linux (loop,gpt7)/kernel boot=local noresume noswap loglevel=7 disablevmx=off \
                cros_secure cros_debug loop.max_part=16 img_part=$img_part img_path=$img_path \
                lsm.module_locking=0 add_efi_memmap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0
        initrd (loop,gpt7)/initramfs.img
}

**Comment by sebanc** [comment]
Hi,

That's actually the most difficult part "installing the grub bootloader from windows" which is not documented for this reason. The issue is that Grub2Win or other windows methods do not seem to work and I have never really used them.

Generally, you would need to replace the grubx64.efi from grub2win on windows efi partition with the crunch one (that you will find on github or in /efi/boot on partition 12) and to copy your configuration in the same folder as "grub.cfg".

If you have enough storage, installing a linux distro is probably an easier way.

**Comment by ericksontx** [comment]
FIXED.

Likely cause was my own over-installing and testing so many OS's back and forth.

Starting from zero - booted from linux live USB. Deleted ALL partitions on HDD - including p1 /EFI partition. Run mr chromebox script. Clear UEFI NVRAM.

Delete any Eve/Pixelbook device entries in your device list / logged in devices in your Google Account to ensure no TPM conflicts with Crunch instance.

Then reboot with Windows install USB, install windows as normal.

When done then reboot with Crunch USB drive. Crunch will upgrade trackpad back to Windows-incompatible (will need to flash back when done).

Perform hard disk install as per dual-boot instructions on Crunch readme. make sure to unmount at end, do not close shell. Highlight and copy grub entry output at end of script. Open up Google Keep (or similar cross platform note app you can access from Windows, or email yourself) and paste grub entry into new note.

Reboot into Windows. Install Grub2win. Once done , within Grub2win edit UEFI boot order, make Grub2Win the default.  boot. In Grub2win, add new entry to boot list. For OS type choose custom code, in custom code entry paste in that grub entry you saved.

Apply and hit ok, and then close out of Grub2win. Reboot. 

Grub2win's boot menu should appear. Select your custom entry. 

Chrome should now boot, with everything working - network, sound,  brightness control.

Once verified, power off and then insert your linux live USB and boot from that. Then run MrChromebox's script and downgrade touchpad firmware.

Touchpad will function again in Windows. 

Fin.

**Comment by ericksontx** [comment]
I had also tried installing Crunch solo on a clean disk with new EFI partition - I ran into the same problem as earlier not being able to login. So Crunch will work on a straight HDD install as well without TPM issues provided the Google account devices list has been cleaned.

So my issues with Crunch on solo and dual install were related.

Closing this one. 

Sebanc will there be a Crunch 83 once Brunch 83 is finalized? Or will the Crunch 80 package work still work fine with Eve 83?

Thanks again for all the work, now have 5 machines all running Brunch or Crunch.

**Comment by sebanc** [comment]
Happy to see that you got it working :)

Crunch is much closer to stock chromeos, it should work fine unless there is a completer structure change in chromeos. The r80 release should therefore work fine with r83 or even beta / dev channles. The things that are most likely to break at some point are qemu and nano added packages which might need to be rebuilt against newer chromeos libraries but that's probably not a real issue.

I will try to provide an updated release at some point but mainly to add new features, I am still thinking about how to do it but I will try to prevent touchpad firmware from being updated.
